services:
  app:
    tty: true
    stdin_open: true

    image: container-vmiiy
    environment:
      - FLASK_DEBUG=1
    build:
      context: ./src
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: ./src/web
        target: /usr/src/app
